include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  errors:
    invalid_use_of_visible_for_testing_member: ignore
    invalid_use_of_internal_member: ignore

linter:
  rules:
    avoid_print: false